### ISSUE TITLE
Firefox Sync doesn't work when flagger is activated

### ISSUE THREAD

**Issue by blankoworld** [rubbingalcoholic/flagger#7]
Hi,

Using Firefox Sync and Flagger.io, I encount problems using Firefox Sync when Flagger is active.

I don't know what's the error, the system just said me that id/password is wrong. Then I put flagger on "off" and Firefox Sync works!

I'm available if needed some supplementary info.

**Comment by rubbingalcoholic** [comment]
Thanks for the report. Fixed with https://github.com/rubbingalcoholic/flagger/commit/f72bf8435b537b811271185262c462a1b12b825a

You can download the new add-on on [the site](https://flagger.io), or directly from https://flagger.io/addon/firefox/flagger-1.3.1.xpi
